<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jair Barrera">

<title>Avance Informe Final</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Informe_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Informe_final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Informe_final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Informe_final_files/libs/quarto-html/popper.min.js"></script>
<script src="Informe_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Informe_final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Informe_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Informe_final_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Informe_final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Informe_final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<<<<<<< HEAD
<link href="Informe_final_files/libs/bootstrap/bootstrap-ebda192607b4aaa0c2c12f42de2f2d18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
=======
<link href="Informe_final_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
>>>>>>> 3743caf96908f317cc754531b6b5100230765a57

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<<<<<<< HEAD
<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link active" data-scroll-target="#objetivo">Objetivo</a></li>
  <li><a href="#hipótesis" id="toc-hipótesis" class="nav-link" data-scroll-target="#hipótesis">Hipótesis</a></li>
  <li><a href="#análisis-inferencial" id="toc-análisis-inferencial" class="nav-link" data-scroll-target="#análisis-inferencial">Análisis inferencial</a></li>
  </ul>
</nav>
</div>
=======
<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

>>>>>>> 3743caf96908f317cc754531b6b5100230765a57
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Avance Informe Final</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Jair Barrera </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">24 de junio de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="objetivo" class="level2">
<h2 class="anchored" data-anchor-id="objetivo">Objetivo</h2>
<p>Se busca dar respuesta a la siguiente pregunta: <strong>¿Difiere el impacto del Cadmio (Cd) sobre la producción de biomasa y la acumulación de metabolitos secundarios foliares al comparar la especie invasora (<em>Alternanthera philoxeroides</em>) con la especie nativa (<em>Alternanthera sessilis</em>)?</strong>.<br>
<br>
Y cumplir los siguientes objetivos:</p>
<ul>
<li><p>Analizar la asignación de biomasa: Describir y comparar la distribución de la masa seca entre la raíz y el tallo (relación raíz/tallo) en ambas especies bajo condiciones de control y tratamiento con cadmio.</p></li>
<li><p>Explorar los costos de tolerancia: Determinar la relación existente entre la inversión en taninos y el crecimiento global (biomasa seca total) para identificar posibles costos energéticos de defensa en cada especie.</p></li>
<li><p>Evaluar el daño físico frente a la absorción: Caracterizar el porcentaje de área foliar lesionada en función de la concentración de cadmio acumulado en las hojas.</p></li>
</ul>
</section>
<section id="hipótesis" class="level2">
<h2 class="anchored" data-anchor-id="hipótesis">Hipótesis</h2>
<section id="para-la-biomasa-total" class="level4">
<h4 class="anchored" data-anchor-id="para-la-biomasa-total">Para la Biomasa Total:</h4>
<ul>
<li><span class="math inline">\(H_0\)</span> (Hipótesis Nula): El efecto de la exposición al Cadmio sobre la producción de biomasa es idéntico en <em>A. philoxeroides</em> y <em>A. sessilis</em>.</li>
<li><span class="math inline">\(H_1\)</span> (Hipótesis Alternativa): El efecto de la exposición al Cadmio sobre la producción de biomasa difiere significativamente entre ambas especies.</li>
</ul>
</section>
<section id="para-la-concentración-de-taninos" class="level4">
<h4 class="anchored" data-anchor-id="para-la-concentración-de-taninos">Para la Concentración de Taninos:</h4>
<ul>
<li><p><span class="math inline">\(H_0\)</span> (Hipótesis Nula): La respuesta en la acumulación de taninos foliares ante la presencia de Cadmio no difiere entre la especie invasora (<em>A. philoxeroides</em>) y la especie nativa (<em>A. sessilis</em>).</p></li>
<li><p><span class="math inline">\(H_1\)</span> (Hipótesis Alternativa): La acumulación de taninos foliares inducida por la presencia de Cadmio difiere significativamente entre ambas especies.</p></li>
</ul>
</section>
</section>
<section id="análisis-inferencial" class="level2">
<h2 class="anchored" data-anchor-id="análisis-inferencial">Análisis inferencial</h2>
<<<<<<< HEAD
<p>Para dar respuesta a la pregunta central se busca realizar dos modelos anova independientes (Uno para biomasa y otro para taninos) siempre y cuando se cumplan los supuestos.Si la interacción es significativa, se procede con una prueba post-hoc de Tukey (Tukey HSD) para comparar pares específicos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value   Pr(&gt;F)    
especie              1  3.594   3.594   22.56 1.46e-05 ***
tratamiento          1 31.047  31.047  194.90  &lt; 2e-16 ***
especie:tratamiento  1  2.153   2.153   13.52 0.000532 ***
=======
<p>Para dar respuesta a la pregunta central se busca realizar dos modelos anova independientes (Uno para biomasa y otro para taninos).Si la interacción es significativa, se procede con una prueba post-hoc de Tukey (Tukey HSD) para comparar pares específicos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Especie              1  3.594   3.594   22.56 1.46e-05 ***
Tratamiento          1 31.047  31.047  194.90  &lt; 2e-16 ***
Especie:Tratamiento  1  2.153   2.153   13.52 0.000532 ***
>>>>>>> 3743caf96908f317cc754531b6b5100230765a57
Residuals           56  8.921   0.159                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<<<<<<< HEAD
<p><em>Prueba de supuestos</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(anova_biomasa)
W = 0.97639, p-value = 0.2952</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  3  0.6331 0.5968
      56               </code></pre>
</div>
</div>
=======
>>>>>>> 3743caf96908f317cc754531b6b5100230765a57
<p>Se encontró un efecto de interacción altamente significativo entre la especie y el tratamiento con cadmio sobre la producción de biomasa seca total (F = 13.52, p &lt; 0.001). Este resultado confirma que el efecto inhibitorio del cadmio sobre la biomasa no afecta por igual a ambas especies. Asimismo, se detectaron diferencias significativas independientes tanto para el factor especie.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

<<<<<<< HEAD
Fit: aov(formula = masa_total_g ~ especie * tratamiento, data = datos_eda)

$`especie:tratamiento`
=======
Fit: aov(formula = Masa_total_g ~ Especie * Tratamiento, data = datos_eda)

$`Especie:Tratamiento`
>>>>>>> 3743caf96908f317cc754531b6b5100230765a57
                                                   diff        lwr        upr
A. sessilis:Cd-A. philoxeroides:Cd           -0.8683473 -1.2542443 -0.4824503
A. philoxeroides:control-A. philoxeroides:Cd  1.0598340  0.6739370  1.4457310
A. sessilis:control-A. philoxeroides:Cd       0.9491853  0.5632883  1.3350823
A. philoxeroides:control-A. sessilis:Cd       1.9281813  1.5422843  2.3140783
A. sessilis:control-A. sessilis:Cd            1.8175327  1.4316357  2.2034297
A. sessilis:control-A. philoxeroides:control -0.1106487 -0.4965457  0.2752483
                                                 p adj
A. sessilis:Cd-A. philoxeroides:Cd           0.0000011
A. philoxeroides:control-A. philoxeroides:Cd 0.0000000
A. sessilis:control-A. philoxeroides:Cd      0.0000001
A. philoxeroides:control-A. sessilis:Cd      0.0000000
A. sessilis:control-A. sessilis:Cd           0.0000000
A. sessilis:control-A. philoxeroides:control 0.8723229</code></pre>
</div>
</div>
<p>La prueba de comparaciones post-hoc confirmó que en condiciones de control no existieron diferencias estadísticamente significativas en la biomasa seca total entre ambas especies (p = 0.872). Si bien la exposición a cadmio indujo una disminución significativa de la biomasa en ambas plantas, la magnitud del impacto difirió entre ellas: Alternanthera sessilis sufrió una pérdida promedio de 1.82g respecto a su control, mientras que Alternanthera philoxeroides registró una reducción de 1.06g. En consecuencia, bajo tratamiento con cadmio, la especie invasora (A. philoxeroides) conservó una biomasa promedio significativamente mayor en comparación con la especie nativa (A. sessilis) (diferencia = -0.87g, evidenciando un desempeño vegetativo superior bajo estrés por metales pesados.</p>
<<<<<<< HEAD
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(anova_taninos)
W = 0.98472, p-value = 0.6557</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value  Pr(&gt;F)  
group  3  2.5472 0.06503 .
      56                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value Pr(&gt;F)
especie              1  0.124  0.1238   0.299  0.587
tratamiento          1  0.381  0.3813   0.921  0.341
especie:tratamiento  1  0.650  0.6499   1.570  0.215
Residuals           56 23.181  0.4140               </code></pre>
</div>
</div>
<p>El análisis de varianza para la concentración de taninos foliares no mostró un efecto de interacción significativo entre la especie y el tratamiento. De igual forma, no se observaron diferencias estadísticamente significativas para los efectos principales de especie ni de tratamiento. En consecuencia, los promedios globales de concentración de taninos se mantuvieron homogéneos entre los grupos evaluados. Este es un resultado que se contrastará con la relación mostrada en el informe exploratorio.</p>
<p><strong>Objetivo 1</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Informe_final_files/figure-html/objetivo%201-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(anova_rt)
W = 0.9664, p-value = 0.09714</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  3  1.7852 0.1605
      56               </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value   Pr(&gt;F)    
especie              1 0.0153 0.01533   0.946    0.335    
tratamiento          1 0.2911 0.29114  17.973 8.46e-05 ***
especie:tratamiento  1 0.0090 0.00896   0.553    0.460    
Residuals           56 0.9071 0.01620                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = datos_eda$`relacion_r/t` ~ especie * tratamiento, data = datos_eda)

$tratamiento
                 diff        lwr         upr    p adj
control-Cd -0.1393183 -0.2051491 -0.07348744 8.46e-05</code></pre>
</div>
</div>
<p>Aquí solo muestra diferenccia significativa en el tratamiento.</p>
<p><strong>objetivo 2</strong></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Informe_final_files/figure-html/fig-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Análisis de correlación lineal entre la biomasa seca total (g) y la concentración de taninos foliares (mg/g) en <em>Alternanthera philoxeroides</em> y <em>Alternanthera sessilis</em> bajo condiciones de control y exposición a cadmio (Cd). Se incluye el coeficiente de correlación de Pearson (R) para cada escenario.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>objetivo 3</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Informe_final_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `lesión_foliar_(%)` ~ `Cd_hoja_mg/g` * especie, 
    data = datos_eda)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2015 -1.3112 -0.3675  1.4072  6.0932 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       11.22171    0.59453  18.875  &lt; 2e-16 ***
`Cd_hoja_mg/g`                    -0.26582    0.02870  -9.262 6.83e-13 ***
especieA. sessilis                 0.17621    0.82973   0.212    0.833    
`Cd_hoja_mg/g`:especieA. sessilis -0.01955    0.05400  -0.362    0.719    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.212 on 56 degrees of freedom
Multiple R-squared:  0.7035,    Adjusted R-squared:  0.6876 
F-statistic: 44.28 on 3 and 56 DF,  p-value: 8.446e-15</code></pre>
</div>
</div>
=======
>>>>>>> 3743caf96908f317cc754531b6b5100230765a57
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>